metadataPackage_1520984274069/objects/GRAXSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>GRAX by Harding Point Settings. https://grax.io</description>
    <label>GRAX Settings</label>
    <fields>
        <fullName>GRAX_Flow_URL__c</fullName>
        <defaultValue>"https://db-fyy9k3vu59gn11jzpimp.graphenedb.com:24780"</defaultValue>
        <label>GRAX Flow URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

GRAXConnect/main/default/classes/GRAXFlow.cls
public with sharing class GRAXFlow {
    public GRAXFlow() {

	    	if (GRAXSettings.IsConfigured()==false)
	    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please complete <a href="/one/one.app#/n/GRAX_DEPLOY">GRAX Configuration</a>.'));
    
    }
    
    public string getPropURLToDisplay() { 
    	    String flowUrl = 'https://grax.io';
    		GRAXSettings__c graxsettings = GRAXSettings__c.getOrgDefaults();
    		if (graxsettings.GRAX_Flow_URL__c!=null)
        		flowUrl = graxsettings.GRAX_Flow_URL__c; 
        return flowUrl;
    }
    
    public pagereference connect(){
        pagereference p=new pagereference(getPropURLToDisplay());
        return p;
    }
    
}