metadataPackage_1521078825898/objects/Grax_Mapped_Field__mdt.object
<CustomObject>
    <label>Grax Mapped Field</label>
    <pluralLabel>Grax Mapped Fields</pluralLabel>
    <fields>
        <fullName>Column_Name__c</fullName>
        <defaultValue>" "</defaultValue>
        <inlineHelpText>Name of the table column</inlineHelpText>
        <label>Column Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <inlineHelpText>This is the name the name of the field to display as shown in the Graphene DB</inlineHelpText>
        <label>Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format_Type__c</fullName>
        <defaultValue>"text"</defaultValue>
        <label>Format Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>currency</fullName>
                    <default>true</default>
                    <label>currency</label>
                </value>
                <value>
                    <fullName>date</fullName>
                </value>
                <value>
                    <fullName>email</fullName>
                </value>
                <value>
                    <fullName>location</fullName>
                </value>
                <value>
                    <fullName>number</fullName>
                </value>
                <value>
                    <fullName>percent</fullName>
                </value>
                <value>
                    <fullName>phone</fullName>
                </value>
                <value>
                    <fullName>text</fullName>
                </value>
                <value>
                    <fullName>url</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <defaultValue>"Opportunity"</defaultValue>
        <inlineHelpText>The Salesforce API name of the object</inlineHelpText>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Order from left to right on the table we want the field displayed</inlineHelpText>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

metadataPackage_1520984274069/objects/GRAXSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>GRAX by Harding Point Settings. https://grax.io</description>
    <label>GRAX Settings</label>
</CustomObject>

metadataPackage_1521078825898/classes/GraxRemoteAccountController.cls
public with sharing class GraxRemoteAccountController {

	@AuraEnabled
	public static Map<String, Object> getAccounts(Id accountId) {

		Account account = getAccount(accountId);

		Map<String, Object> result = null;

		if (account != null && account.Name != null) {

			result = Neo4jAdapter.getAccountsByName(account.Name);
		}

		return result;
	}

	@AuraEnabled
	public static GRAXSettings__c getMainSettings() {

		// return Grax_General_Settings__c.getOrgDefaults();
		return GRAXSettings__c.getOrgDefaults();
	}

	@AuraEnabled
	public static Map<String, Object> getAccountOpportunities(String[] nodeIds) {
		Map<String, Object> result = Neo4jAdapter.getAccountOpportunities(nodeIds);
		System.debug(JSON.serializePretty(result));
		return result;
	}

	@AuraEnabled
	public static Map<String, Object> getAccountContacts(String[] nodeIds) {
		Map<String, Object> result = Neo4jAdapter.getAccountContacts(nodeIds);
		System.debug(JSON.serializePretty(result));
		return result;
	}

	@AuraEnabled
	public static Map<String, Object> getAccountCases(String[] nodeIds) {
		Map<String, Object> result = Neo4jAdapter.getAccountCases(nodeIds);
		System.debug(JSON.serializePretty(result));
		return result;
	}

	@AuraEnabled
	public static Map<String, Grax_Mapped_Field__mdt[]> getColumnLabels() {

		Map<String, Grax_Mapped_Field__mdt[]> result = new Map<String, Grax_Mapped_Field__mdt[]>();

		Grax_Mapped_Field__mdt[] labels = new Grax_Mapped_Field__mdt[] {};
		labels = [SELECT
						Column_Name__c,
						Field_Name__c,
						Format_Type__c,
						Object_Name__c,
						Sort_Order__c
					FROM Grax_Mapped_Field__mdt
					WHERE Object_Name__c != null
					ORDER BY Object_Name__c, Sort_Order__c];

		for (Grax_Mapped_Field__mdt label :labels) {

			if (!result.containsKey(label.Object_Name__c)) {
				result.put(label.Object_Name__c, new Grax_Mapped_Field__mdt[] {});
			}

			// labeling with lowercase
			result.get(label.Object_Name__c).add(label);
		}

		return result;
	}

	private static Account getAccount(Id accountId) {

		Account[] result = new Account[] {};
		result = [SELECT Name FROM Account WHERE Id = :accountId];
		return result.isEmpty() ? null : result[0];
	}

}