mdapioutput/objects/GRAX_Archive_Process__c.object
<CustomObject>
    <label>GRAX Archive Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Archive Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Archive Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Async_Records_Successfully_Sent__c</fullName>
        <label># Async Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Async_Records_to_Process__c</fullName>
        <label># Async Records to Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Archive Processes</relationshipLabel>
        <relationshipName>GRAX_Archive_Processes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Records_Successfully_Sent__c</fullName>
        <label># Records Successfully Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_To_Process__c</fullName>
        <label># Records To Process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Records_To_Process__c &gt; 0 &amp;&amp; Records_Successfully_Sent__c = Records_To_Process__c &amp;&amp; Async_Records_Successfully_Sent__c = Async_Records_to_Process__c, &#39;Ready to Delete&#39;, &#39;Waiting to Complete Processing&#39;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>GRAX Data Record</description>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error_Message</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GRAX_Schedule_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GRAX_Schedule_Process</description>
        <label>GRAX Schedule Process</label>
        <referenceTo>GRAX_Schedule_Process__c</referenceTo>
        <relationshipLabel>GRAX Data Records</relationshipLabel>
        <relationshipName>GRAX_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sent_Date__c</fullName>
        <description>Last_Sent_Date</description>
        <label>Last Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

GRAXConnect/main/default/objects/GRAX_Data_Record__c/fields/GRAX_Archive_Process__c.field-meta.xml
<CustomField>
    <fullName>GRAX_Archive_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRAX Archive Process</label>
    <referenceTo>GRAX_Archive_Process__c</referenceTo>
    <relationshipLabel>GRAX Data Records</relationshipLabel>
    <relationshipName>GRAX_Data_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

GRAXConnect/main/default/objects/GRAX_Data_Record__c/fields/Records_To_Process__c.field-meta.xml
<CustomField>
    <fullName>Records_To_Process__c</fullName>
    <label># Records To Process</label>
    <summaryForeignKey>GRAX_Data_Record_Id__c.GRAX_Data_Record__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapioutput/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapioutput/objects/GRAX_Schedule_Process__c.object
<CustomObject>
    <label>GRAX Schedule Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Schedule Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Schedule Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Archive</description>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <description>Date_Field</description>
        <label>Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Run_Date__c</fullName>
        <description>Next_Run_Date</description>
        <label>Next Run Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Object_Name</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date__c</fullName>
        <description>Schedule_Start_Date</description>
        <label>Schedule Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Time__c</fullName>
        <description>Schedule_Start_Time</description>
        <label>Schedule Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Type__c</fullName>
        <description>Schedule_Type</description>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_Criteria__c</fullName>
        <description>Select_Criteria</description>
        <label>Select Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main Object not modified</fullName>
                </value>
                <value>
                    <fullName>Main Object and Children not modified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <description>Target_Date</description>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

mdapioutput/objects/GRAXQuery__c.object
<CustomObject>
    <description>This object is used to store the custom fields and filters used by GRAX Connect</description>
    <label>GRAX : Object Configuration</label>
    <nameField>
        <displayFormat>GRAX-{000000}</displayFormat>
        <label>GRAXQueries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX : Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapioutput/classes/GRAXBatchToCleanDataRecordsTest.cls
/*****************************************************************************************
Name              : GRAXBatchToCleanDataRecordsTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner       04/17/2018				David Mackey        https://app.asana.com/0/326600806074978/633149554508924/f
******************************************************************************************/
@isTest
private class GRAXBatchToCleanDataRecordsTest {
    @isTest(seeAllData = false)
    static void GRAXBatchToCleanDataRecordsTest() {

        // To delete
        GRAX_Schedule_Process__c gsp = new GRAX_Schedule_Process__c();
        gsp.Object_Name__c = 'GRAXQuery__c';
        gsp.Date_Field__c = 'CreatedDate';
        gsp.Target_Date__c = Date.today().addDays(-3);
        gsp.Select_Criteria__c = 'Main Object not modified';
        gsp.Schedule_Type__c = 'Once';
        gsp.Schedule_Start_Date__c = Date.today();
        gsp.Schedule_Start_Time__c = '23:00';
        gsp.Next_Run_Date__c = Datetime.now();
        gsp.Archive__c = true;
        insert gsp;

        GRAX_Archive_Process__c archiveProc = new GRAX_Archive_Process__c();
        archiveProc.GRAX_Schedule_Process__c = gsp.Id;
        archiveProc.Async_Records_Successfully_Sent__c = 0;
        archiveProc.Async_Records_to_Process__c = 0;
        archiveProc.Records_Successfully_Sent__c = 2;
        archiveProc.Records_To_Process__c = 0;
        insert archiveProc;

        // To delete
        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
        dr.Salesforce_Object__c = 'GRAXQuery__c';
        dr.Status__c = 'Sent Successful';
        dr.of_Times_Sent__c = 1;
        dr.Error_Message__c = null;
        //dr.GRAX_Archive_Process__c = archiveProc.Id;
        dr.Last_Sent_Date__c = Date.today().addDays(-3);

        // To delete
        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
        dr2.Salesforce_Object__c = 'GRAXQuery__c';
        dr2.Status__c = 'Sent Successful';
        dr2.of_Times_Sent__c = 1;
        dr2.Error_Message__c = null;
        dr2.GRAX_Archive_Process__c = archiveProc.Id;
        dr2.Last_Sent_Date__c = Date.today().addDays(-2);

        GRAX_Data_Record__c dr3 = new GRAX_Data_Record__c();
        dr3.Salesforce_Object__c = 'GRAXQuery__c';
        dr3.Status__c = 'Sent Successful';
        dr3.of_Times_Sent__c = 1;
        dr3.Error_Message__c = null;
        dr3.GRAX_Archive_Process__c = archiveProc.Id;
        dr3.Last_Sent_Date__c = Date.today();

		insert new List<GRAX_Data_Record__c> { dr, dr2, dr3 };

        // To delete
        GRAX_Data_Record_Id__c dri = new GRAX_Data_Record_Id__c();
        dri.GRAX_Data_Record__c = dr.Id;

        // To delete
        GRAX_Data_Record_Id__c dri2 = new GRAX_Data_Record_Id__c();
        dri2.GRAX_Data_Record__c = dr2.Id;

        GRAX_Data_Record_Id__c dri3 = new GRAX_Data_Record_Id__c();
        dri3.GRAX_Data_Record__c = dr3.Id;

        insert new List<GRAX_Data_Record_Id__c> { dri, dri2, dri3 };

        Test.startTest();
        database.executebatch(new GRAXBatchToCleanDataRecords(0));
        Test.stopTest();
        
        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record__c WHERE Id IN : new List<GRAX_Data_Record__c>{dr, dr2, dr3}].size());
        System.assertEquals(1, [SELECT Id FROM GRAX_Data_Record_Id__c WHERE Id IN : new List<GRAX_Data_Record_Id__c>{dri, dri2, dri3}].size());
        System.assertEquals(1, [SELECT Id FROM GRAX_Archive_Process__c WHERE Id IN : new List<GRAX_Archive_Process__c>{archiveProc}].size());
    }
}