mdapioutput/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>GRAX Data Record</description>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Error_Message</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object__c</fullName>
        <description>Salesforce_Object</description>
        <label>Salesforce Object</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Times_Sent__c</fullName>
        <description>of_Times_Sent</description>
        <label># of Times Sent</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapioutput/classes/GRAXBatchToResendDataRecordsTest.cls
/*****************************************************************************************
Name              : GRAXBatchToResendDataRecordsTest
Description       : 
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner       04/17/2018				David Mackey        https://app.asana.com/0/326600806074978/633149554508924/f
******************************************************************************************/
@isTest
private class GRAXBatchToResendDataRecordsTest {
    @isTest(seeAllData = false)
    static void GRAXBatchToResendDataRecordsTest() {
        GRAX_Data_Record__c dr = new GRAX_Data_Record__c();
		dr.Salesforce_Object__c = 'Test';
		dr.Status__c = 'Error';
		dr.of_Times_Sent__c = 4;

        GRAX_Data_Record__c dr2 = new GRAX_Data_Record__c();
		dr2.Salesforce_Object__c = 'Test';
		dr2.Status__c = 'Error';
		dr2.of_Times_Sent__c = 5;

		insert new List<GRAX_Data_Record__c> { dr, dr2 };

		Attachment att = new Attachment();
		att.Name = 'request.txt';
		att.Body = Blob.valueOf('{}');
		att.ParentId = dr.Id;

        Attachment att2 = new Attachment();
		att2.Name = 'request.txt';
		att2.Body = Blob.valueOf('{}');
		att2.ParentId = dr2.Id;

        insert new List<Attachment> { att, att2 };

        GRAXUnitTest.SingleRequestMock fakeResponse = new GRAXUnitTest.SingleRequestMock(200, '{"message": "Test successful"}', 'http://test.grax.io/applications/neo4j/configure', null);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        database.executebatch(new GRAXBatchToResendDataRecords());

        Test.stopTest();

        Map<Id, GRAX_Data_Record__c> dataRecords2Check = new Map<Id, GRAX_Data_Record__c>([SELECT Id, Status__c, of_Times_Sent__c, Error_Message__c FROM GRAX_Data_Record__c]);

        System.assertEquals(5, dataRecords2Check.get(dr.Id).of_Times_Sent__c);
        System.assertEquals(null, dataRecords2Check.get(dr.Id).Error_Message__c);
        System.assertEquals('Sent Successful', dataRecords2Check.get(dr.Id).Status__c);

        System.assertEquals(5, dataRecords2Check.get(dr2.Id).of_Times_Sent__c);
        System.assertEquals('Error', dataRecords2Check.get(dr2.Id).Status__c);
    }
}