mdapioutput/objects/GRAXQuery__c.object
<CustomObject>
    <description>This object is used to store the custom fields and filters used by GRAX Connect</description>
    <label>GRAX : Object Configuration</label>
    <nameField>
        <displayFormat>GRAX-{000000}</displayFormat>
        <label>GRAXQueries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX : Object Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Enable_Audit_Log__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Audit Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <label>Filter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GRAX_Configured__c</fullName>
        <label>GRAX Configured</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hourly_Synch_Period__c</fullName>
        <label>Hourly Synch Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Synch__c</fullName>
        <label>Last Synch</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <externalId>true</externalId>
        <label>ObjectName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_By__c</fullName>
        <label>Order By</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Fields__c</fullName>
        <label>Selected Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Records_Processed__c</fullName>
        <label>Total Records Processed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>graxconfig__c</fullName>
        <label>graxconfig</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

mdapioutput/objects/GRAXSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>GRAX by Harding Point Settings. https://grax.io</description>
    <label>GRAX Settings</label>
    <fields>
        <fullName>ApiToken__c</fullName>
        <description>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_APITOKEN</description>
        <inlineHelpText>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_APITOKEN</inlineHelpText>
        <label>ApiToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRAX_API_Url__c</fullName>
        <label>GRAX API Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>GatewayToken__c</fullName>
        <description>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_GATEWAYTOKEN</description>
        <inlineHelpText>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_GATEWAYTOKEN</inlineHelpText>
        <label>GatewayToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LicenseToken__c</fullName>
        <description>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_LICENSETOKEN</description>
        <inlineHelpText>GRAX Settings : Heroku Setting ENGAGEMENTGRAPH_LICENSETOKEN</inlineHelpText>
        <label>LicenseToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postgres_URL__c</fullName>
        <description>Postgres URL used for Audit Trail</description>
        <inlineHelpText>Postgres URL used for Audit Trail</inlineHelpText>
        <label>PostgresURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>graphdburl__c</fullName>
        <description>GRAX Settings : Heroku Setting GRAPHENEDB_URL</description>
        <inlineHelpText>GRAX Settings : Heroku Setting GRAPHENEDB_URL</inlineHelpText>
        <label>graphdburl</label>
        <type>Url</type>
    </fields>
</CustomObject>

mdapioutput/classes/GRAXSettings.cls
/* --------------------------------------------------------------------------
 * This file is subject to the terms and conditions defined in
 * file https://github.com/HardingPoint/GRAXForSFDC/blob/master/LICENSE,
 * which is part of this source code package.
 * --------------------------------------------------------------------------
 *          Copyright (c) 2017-2018 Harding Point
 *                  All rights reserved
 * --------------------------------------------------------------------------
 * Support:	Support@Grax.io
 * Website:	https://grax.io
 * Github:	https://github.com/HardingPoint/GRAXForSFDC
 * License:	https://github.com/HardingPoint/GRAXForSFDC/blob/master/LICENSE
 * --------------------------------------------------------------------------*/

public virtual class GRAXSettings {

	public Boolean ProperlyConfigured = false; 
	public String graphdburl = '';
	public String LicenseToken = '';
	public String GatewayToken = '';
	public String ApiToken = '';
	public String PostgresURL = '';
	
	public GRAXSettings__c graxConfig {get;set;}
	
	// Default to the testing URL
	public String ApiURL = 'https://test.hardingpoint.com/v9.3/api';
	public String GRAXDeployURL = 'https://heroku.com/deploy?template=https://github.com/HardingPoint/GRAXEnterprise/blob/master';

	public Boolean isObjectConfigured = false;
	
	// GRAX Saved Query List
	public Map<String,GRAXQuery__c> SynchedObjects = null;
	
	// GRAX Saved Query Singular
	public GRAXQuery__c GRAXQuery = null;
	
	private String ExecutionSource = '';

	public GRAXSettings(String executionSource, String objectName) {
		ExecutionSource = executionSource;
		ProperlyConfigured = Initialize(objectName);
	}

	// Load Settings for Object
	public GRAXSettings(String objectName) {
		ProperlyConfigured = Initialize(objectName);
	}

	// Default Constructor
    public GRAXSettings() {
		ProperlyConfigured = Initialize('');
    }
    
    public void UpdateSettings(){	
    		upsert graxConfig;
    }
    
    // Load the configuration & object settings.
    private Boolean Initialize(String ObjectName){
    		graxConfig = GRAXSettings__c.getOrgDefaults();
		if (graxConfig != null){
			// GRAX Custom Settings Values.
			graphdburl = graxConfig.graphdburl__c;
			LicenseToken = graxConfig.LicenseToken__c;
			GatewayToken = graxConfig.GatewayToken__c;
			PostgresURL = graxConfig.Postgres_URL__c;
			ApiToken = graxConfig.ApiToken__c;
			
			if (graxConfig.GRAX_API_Url__c != '' && graxConfig.GRAX_API_Url__c != null)
				ApiURL=graxConfig.GRAX_API_Url__c;
			
    			if ((graphdburl != null && graphdburl != '')&&			
    				(LicenseToken != null && LicenseToken != '')&&
    				(GatewayToken != null && GatewayToken != '')&&
    				(ApiToken != null && ApiToken != ''))
    				ProperlyConfigured = true;
    		}
    		
    		// GRAX Saved Queries
		SynchedObjects = GRAXSettings.getSynchedObjects();
		
    		GRAXQuery = getSynchedObject(ObjectName);
    		if (GRAXQuery!=null){
    			isObjectConfigured = true;
    		}
    				
    		return ProperlyConfigured;
    }
    
    public static Boolean IsConfigured(){
    		GRAXSettings gx = new GRAXSettings();
    		return gx.ProperlyConfigured;
    }
    
    public GRAXQuery__c getSynchedObject(String ObjectName){
    		if (ObjectName!='')
    			return SynchedObjects.get(ObjectName);
    		else
    			return null;
    }
    
    // Singular place to load settings. If the schema changes this is where you modify it.
    public static Map<String,GRAXQuery__c> getSynchedObjects()
	{
	    		Map<String,GRAXQuery__c> GRAXObjects = new Map<String,GRAXQuery__c>();
	    		List<GRAXQuery__c> queries = [Select Id,Name,Filter__c,GRAX_Configured__c,graxconfig__c,Hourly_Synch_Period__c,Last_Synch__c,ObjectName__c,Order_By__c,Selected_Fields__c,Total_Records_Processed__c,Enable_Audit_Log__c  From GRAXQuery__c];
	    		for (GRAXQuery__c query : queries){
	    			GRAXObjects.put(query.ObjectName__c,query);
	    		}
	    		return GRAXObjects;
	}
	
	// ------------------------------------------------------------------------
	// Should move these to a seperate class
	public void debug(String output){
    		debug('', output, '');
    }
    
    public void debug(String MethodName, String output){
    		debug(MethodName, output, '');
    }
    
    public void debug(String MethodName, String output, String Error){
    		String Source = ExecutionSource;
    		if (Source!='' && MethodName!='')
    			Source += '.' + MethodName;
    		else if (MethodName!='')
    			Source = MethodName;
    		GRAXSettings.debug(Source, output, Error, 0);
    }
    
    public static void debug(String source, String output, String error, Integer level){
    		if (Source!='')
    			Source += ': ';
    		if (error!='')
    			error = ' [GRAX Error] ' + error;
    			
    		System.debug('[GRAX.io] ' + source + output + error);
    }
    // ------------------------------------------------------------------------
}