mdapioutput/objects/GRAX_Archive_Process__c.object
<CustomObject>
    <label>GRAX Archive Process</label>
    <nameField>
        <displayFormat>GRAX-Proc-{0000000}</displayFormat>
        <label>GRAX Archive Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Archive Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Records_To_Process__c &gt; 0 &amp;&amp; Records_Successfully_Sent__c = Records_To_Process__c &amp;&amp; Async_Records_Successfully_Sent__c = Async_Records_to_Process__c, &#39;Ready to Delete&#39;, &#39;Waiting to Complete Processing&#39;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

mdapioutput/objects/GRAX_Data_Record__c.object
<CustomObject>
    <description>GRAX Data Record</description>
    <label>GRAX Data Record</label>
    <nameField>
        <displayFormat>GRAX-{0000000}</displayFormat>
        <label>GRAX Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Last_Sent_Date__c</fullName>
        <description>Last_Sent_Date</description>
        <label>Last Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent Successful</fullName>
                </value>
                <value>
                    <fullName>Not Processed - Queuable Jobs Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

GRAXConnect/main/default/objects/GRAX_Data_Record__c/fields/GRAX_Archive_Process__c.field-meta.xml
<CustomField>
    <fullName>GRAX_Archive_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRAX Archive Process</label>
    <referenceTo>GRAX_Archive_Process__c</referenceTo>
    <relationshipLabel>GRAX Data Records</relationshipLabel>
    <relationshipName>GRAX_Data_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapioutput/objects/GRAX_Data_Record_Id__c.object
<CustomObject>
    <label>GRAX Data Record Id</label>
    <nameField>
        <displayFormat>GRAX-RecId-{000000000}</displayFormat>
        <label>GRAX Data Record Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GRAX Data Record Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>GRAX_Data_Record__c</fullName>
        <label>GRAX Data Record</label>
        <referenceTo>GRAX_Data_Record__c</referenceTo>
        <relationshipLabel>GRAX Data Record Ids</relationshipLabel>
        <relationshipName>GRAX_Data_Record_Ids</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To be Deleted</fullName>
                </value>
                <value>
                    <fullName>Deleted with Master Parent</fullName>
                </value>
                <value>
                    <fullName>Successfully Deleted</fullName>
                </value>
                <value>
                    <fullName>Delete Error</fullName>
                </value>
                <value>
                    <fullName>Sent to GRAX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

GRAXConnect/main/default/classes/GRAXBatchToCleanDataRecords.cls
/*****************************************************************************************
Name              : GRAXBatchToCleanDataRecords
Description       : Clean records that have been sent correctly and are more than 48 hours old.
Revision History  :
Created/Modified by   Created/Modified Date     Requested by        Related Task/Issue     
----------------------------------------------------------------------------------------
1. Leandro Brunner       04/17/2018             David Mackey        https://app.asana.com/0/326600806074978/633149554508924/f
******************************************************************************************/
global class GRAXBatchToCleanDataRecords implements Database.Batchable<sObject> {
    private Map<String, String> queryByObject = new Map<String, String>{
        'GRAX_Data_Record__c' => 'SELECT Id FROM GRAX_Data_Record__c WHERE Status__c = \'Sent Successful\' AND Last_Sent_Date__c < LAST_N_DAYS:2 AND (GRAX_Archive_Process__c = null OR GRAX_Archive_Process__r.Status__c = \'Ready to Delete\')',
        'GRAX_Data_Record_Id__c' => 'SELECT Id FROM GRAX_Data_Record_Id__c WHERE GRAX_Data_Record__r.Status__c = \'Sent Successful\' AND GRAX_Data_Record__r.Last_Sent_Date__c < LAST_N_DAYS:2 AND (GRAX_Data_Record__r.GRAX_Archive_Process__c = null OR GRAX_Data_Record__r.GRAX_Archive_Process__r.Status__c = \'Ready to Delete\')',
        'GRAX_Archive_Process__c' => 'SELECT Id FROM GRAX_Archive_Process__c WHERE Status__c = \'Ready to Delete\''
    };
    private List<String> objects2Execute = new List<String>{'GRAX_Data_Record_Id__c','GRAX_Data_Record__c','GRAX_Archive_Process__c'};
    private Integer currentIndex = 0;
    public String query = '';
    
    public GRAXBatchToCleanDataRecords(Integer currentIndex){
        this.currentIndex = currentIndex;
        this.query = queryByObject.get(objects2Execute[currentIndex]);
    }
    
    global Database.querylocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(this.query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        delete scope;
        Database.emptyRecycleBin(scope);
    }

    global void finish(Database.BatchableContext BC){
        if(currentIndex < objects2Execute.size() - 1){
            currentIndex++;
            GRAXBatchToCleanDataRecords b = new GRAXBatchToCleanDataRecords(currentIndex);
            database.executebatch(b, 1000);
        }
    }
}